'use client';

import { 
  Search, Key, PlusCircle, Activity, Power, Trash2, ShieldCheck 
} from 'lucide-react';

const mockCoupons: any[] = [];

export default function CouponsPage() {
  return (
    <div className="space-y-6 animate-fade-in pb-10">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h1 className="text-3xl font-black text-gray-900 dark:text-white">Coupon Codes</h1>
          <p className="text-gray-500 dark:text-gray-400 mt-1">Generate and track individual promotional codes.</p>
        </div>
        <button className="flex items-center gap-2 bg-gradient-to-r from-[#ea580c] to-[#c2410c] text-white px-5 py-2.5 rounded-xl font-bold shadow-lg shadow-orange-500/30 hover:-translate-y-0.5 transition-all">
          <PlusCircle className="w-5 h-5" /> Bulk Generate
        </button>
      </div>

      <div className="bg-white dark:bg-[#1e293b] p-4 rounded-2xl shadow-sm border border-gray-100 dark:border-gray-800 flex flex-wrap gap-4">
        <div className="relative flex-1 md:max-w-md">
          <Search className="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" />
          <input type="text" placeholder="Search coupon code..." className="w-full pl-10 pr-4 py-2.5 bg-gray-50 dark:bg-[#0f172a] border border-gray-200 dark:border-gray-700 rounded-xl text-sm focus:border-[#ea580c] outline-none dark:text-white uppercase font-mono" />
        </div>
        <select className="bg-gray-50 dark:bg-[#0f172a] border border-gray-200 dark:border-gray-700 rounded-xl px-4 py-2.5 text-sm font-bold text-gray-700 dark:text-gray-300 outline-none">
          <option>All Statuses</option>
          <option>Active</option>
          <option>Expired</option>
        </select>
      </div>

      <div className="bg-white dark:bg-[#1e293b] rounded-3xl shadow-sm border border-gray-100 dark:border-gray-800 overflow-hidden">
        <table className="w-full text-left whitespace-nowrap">
          <thead className="bg-gray-50 dark:bg-[#0f172a] text-gray-500 dark:text-gray-400 text-xs font-bold uppercase tracking-wider">
            <tr>
              <th className="px-6 py-4">Coupon Code</th>
              <th className="px-6 py-4">Discount</th>
              <th className="px-6 py-4">Usage Track</th>
              <th className="px-6 py-4">Generated By</th>
              <th className="px-6 py-4">Status</th>
              <th className="px-6 py-4 text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-100 dark:divide-gray-800">
            {mockCoupons.length === 0 && (
              <tr>
                <td colSpan={6} className="px-6 py-16 text-center text-gray-500 dark:text-gray-400">
                  <div className="flex flex-col items-center justify-center">
                    <Key className="w-12 h-12 mb-3 text-gray-300 dark:text-gray-600" />
                    <p className="font-medium text-lg">No coupon codes found.</p>
                    <p className="text-sm mt-1">Generate individual promotional codes here.</p>
                  </div>
                </td>
              </tr>
            )}
            {mockCoupons.map((coupon) => (
              <tr key={coupon.id} className="hover:bg-orange-50/30 dark:hover:bg-[#0f172a]/50 transition-colors">
                <td className="px-6 py-4">
                  <div className="flex items-center gap-3">
                    <div className="p-2 bg-gray-100 dark:bg-gray-800 rounded-lg text-gray-500"><Key className="w-4 h-4" /></div>
                    <span className="font-mono font-black text-lg text-[#ea580c]">{coupon.code}</span>
                  </div>
                </td>
                <td className="px-6 py-4 font-bold text-gray-900 dark:text-white">{coupon.type}</td>
                <td className="px-6 py-4">
                  <div className="flex items-center gap-2">
                    <Activity className="w-4 h-4 text-gray-400" />
                    <span className="text-sm font-bold text-gray-700 dark:text-gray-300">{coupon.usage}</span>
                  </div>
                </td>
                <td className="px-6 py-4 text-sm text-gray-500 dark:text-gray-400 flex items-center gap-2 mt-2">
                  <ShieldCheck className="w-4 h-4" /> {coupon.generatedBy}
                </td>
                <td className="px-6 py-4">
                  <span className={`px-2.5 py-1 text-xs font-bold rounded-full ${coupon.status === 'Active' ? 'bg-green-100 text-green-700 dark:bg-green-500/10 dark:text-green-400' : 'bg-gray-100 text-gray-600 dark:bg-gray-800 dark:text-gray-400'}`}>
                    {coupon.status}
                  </span>
                </td>
                <td className="px-6 py-4 text-right">
                  <div className="flex items-center justify-end gap-2">
                    <button className={`p-2 rounded-lg transition-colors tooltip-trigger ${coupon.status === 'Active' ? 'text-green-500 hover:bg-green-50 dark:hover:bg-green-900/20' : 'text-gray-400'}`} title="Toggle Status"><Power className="w-4 h-4" /></button>
                    <button className="p-2 text-gray-400 hover:text-red-500 hover:bg-red-50 dark:hover:bg-red-900/20 rounded-lg transition-colors tooltip-trigger" title="Delete"><Trash2 className="w-4 h-4" /></button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
